file_format: "1"
id: kobitokey_o_oyayubi
name: kobitokey-o-oyayubi
type: shield
url: https://github.com/s-katada/kobitokey-o-oyayubi
requires: [seeeduino_xiao_ble]
features:
  - keys
  - pointer
siblings:
  - kobitokey_o_oyayubi_left
  - kobitokey_o_oyayubi_right
