name: Firmware (ZMK)

on:
  push:
    branches: [main]
    paths:
      - "config/**"
      - "build.yaml"
      - ".github/workflows/firmware-zmk.yml"
  pull_request:
    paths:
      - "config/**"
      - "build.yaml"
      - ".github/workflows/firmware-zmk.yml"
  workflow_dispatch:

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3
    with:
      archive_name: kobitokey-o-oyayubi-zmk-firmware
